'use strict'

var titlebar = require('titlebar');

views.Titlebar = Backbone.View.extend({

    el: $('#titlebar'),
    titlebar_el: '#titlebar',
    fullscreen: false,

    titlebar: titlebar(),

    events: {
        'click *[data-toggle=view]': 'openView',
    },

    inner_html_template: _.template(`
        <div id="header">
            <!--
                the comments between each <li>
                get rid of the extra space
                generated by the new line
            -->
            <ul class="header-nav tabs-list" role="tablist">
                <li class="active">
                    <a data-toggle="tab" data-target="#movies-container" aria-expanded="true">Movies</a>
                </li><!--
                --><li>
                    <a data-toggle="tab" data-target="#videos-container">Videos</a>
                </li><!--
                --><li>
                    <a data-toggle="tab" data-target="#complete-collection-container">Complete collection</a>
                </li>
            </ul>

            <ul class="header-nav pull-right">
                <li class="form">
                    <input type="text" placeholder="Search" class="form-control input-sm" name="q">
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        Genre
                        <span class="value"></span>
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu1">
                        <li><a href="#">Title</a></li>
                        <li><a href="#">Year</a></li>
                        <li><a href="#">Rating</a></li>
                    </ul>
                </li><!--
                --><li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        Sort by
                        <span class="value"></span>
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu1">
                        <li><a href="#">Title</a></li>
                        <li><a href="#">Year</a></li>
                        <li><a href="#">Rating</a></li>
                    </ul>
                </li><!--
                --><li>
                    <a class="settings" data-view="settings" data-toggle="view"><i class="fa fa-cog"></i></a>
                </li>
            </ul>

            <div class="clearfix"></div>
        </div>
    `),

    initialize: function() {
        this.render();
    },

    render: function() {
        var titlebar = $(this.titlebar.element).append(
            this.inner_html_template(this)
        );
        this.titlebar.appendTo(this.titlebar_el);
    },

    openView: function() {},

});
